{
 "title": "BE Exporter (gRPC)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "installation",
    "query": "label_values(insolar_light_last_sent_pulse, installation)"
   }
  ]
 },
 "panels": [
  {
   "title": "request error rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{installation=~\"$installation\",grpc_code!=\"OK\"}[1m])) by (grpc_service, grpc_method)",
     "legendFormat": "{{grpc_service}}.{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Pulse Exporter error rate ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{installation=~\"$installation\",grpc_service=\"exporter.PulseExporter\",grpc_code!=\"OK\"}[1m])) by (grpc_method,grpc_code)",
     "legendFormat": "{{grpc_method}} - {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Record Exporter error rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{installation=~\"$installation\",grpc_service=\"exporter.RecordExporter\",grpc_code!=\"OK\"}[1m])) by (grpc_method,grpc_code)",
     "legendFormat": "{{grpc_method}} - {{grpc_code}}"
    }
   ]
  },
  {
   "title": "overall rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{installation=~\"$installation\"}[1m])) by (env)",
     "legendFormat": "in"
    },
    {
     "expr": "sum(rate(grpc_server_msg_sent_total{installation=~\"$installation\"}[1m])) by (env)",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "unary request inbound rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{installation=~\"$installation\",grpc_type=\"unary\"}[1m])) by (grpc_service,grpc_method)",
     "legendFormat": "{{grpc_service}}.{{grpc_method}}"
    }
   ]
  },
  {
   "title": "server_stream request inbound rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{installation=~\"$installation\",grpc_type=\"server_stream\"}[1m])) by (grpc_service,grpc_method)",
     "legendFormat": "{{grpc_service}}.{{grpc_method}}"
    }
   ]
  },
  {
   "title": "percentage of slow unary queries (>10ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100.0 - (\nsum(rate(grpc_server_handling_seconds_bucket{installation=~\"$installation\",grpc_type=\"unary\",le=\"0.01\"}[1m])) by (grpc_service)\n / \nsum(rate(grpc_server_handling_seconds_count{installation=~\"$installation\",grpc_type=\"unary\"}[1m])) by (grpc_service)\n) * 100.0",
     "legendFormat": "{{grpc_service}}"
    }
   ]
  },
  {
   "title": "server_stream request outbound rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_msg_sent_total{installation=~\"$installation\",grpc_type=\"server_stream\"}[1m])) by (grpc_service,grpc_method)",
     "legendFormat": "{{grpc_service}}.{{grpc_method}}"
    }
   ]
  },
  {
   "title": "latency of unary requests, ms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{installation=~\"$installation\",grpc_type=\"unary\"}[1m])) by (grpc_service,le)\n) * 1000",
     "legendFormat": "{{grpc_service}} - 99%-tile"
    },
    {
     "expr": "histogram_quantile(0.90, \n  sum(rate(grpc_server_handling_seconds_bucket{installation=~\"$installation\",grpc_type=\"unary\"}[1m])) by (grpc_service,le)\n) * 1000",
     "legendFormat": "{{grpc_service}} - 90%-tile"
    },
    {
     "expr": "histogram_quantile(0.50, \n  sum(rate(grpc_server_handling_seconds_bucket{installation=~\"$installation\",grpc_type=\"unary\"}[1m])) by (grpc_service,le)\n) * 1000",
     "legendFormat": "{{grpc_service}} - 50%-tile"
    }
   ]
  },
  {
   "title": "latency of server_stream requests, ms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{installation=~\"$installation\",grpc_type=\"server_stream\"}[1m])) by (grpc_service,le)\n) * 1000",
     "legendFormat": "{{grpc_service}} - 99%-tile"
    },
    {
     "expr": "histogram_quantile(0.90, \n  sum(rate(grpc_server_handling_seconds_bucket{installation=~\"$installation\",grpc_type=\"server_stream\"}[1m])) by (grpc_service,le)\n) * 1000",
     "legendFormat": "{{grpc_service}} - 90%-tile"
    },
    {
     "expr": "histogram_quantile(0.50, \n  sum(rate(grpc_server_handling_seconds_bucket{installation=~\"$installation\",grpc_type=\"server_stream\"}[1m])) by (grpc_service,le)\n) * 1000",
     "legendFormat": "{{grpc_service}} - 50%-tile"
    }
   ]
  },
  {
   "title": "average unary request duration, ms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(grpc_server_handling_seconds_sum{installation=~\"$installation\",grpc_type=\"unary\"}[1m])) by (grpc_service,grpc_method)\n/ \nsum(rate(grpc_server_handling_seconds_count{installation=~\"$installation\",grpc_type=\"unary\"}[1m])) by (grpc_service,grpc_method))\n*\n1000",
     "legendFormat": "{{grpc_service}}.{{grpc_method}}"
    }
   ]
  },
  {
   "title": "average server_stream request duration, ms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(grpc_server_handling_seconds_sum{installation=~\"$installation\",grpc_type=\"server_stream\"}[1m])) by (grpc_service,grpc_method)\n/ \nsum(rate(grpc_server_handling_seconds_count{installation=~\"$installation\",grpc_type=\"server_stream\"}[1m])) by (grpc_service,grpc_method))\n*\n1000",
     "legendFormat": "{{grpc_service}}.{{grpc_method}}"
    }
   ]
  },
  {
   "title": "average response stream size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_msg_sent_total{installation=~\"$installation\",grpc_type=\"server_stream\"}[1m])) by (grpc_service,grpc_method)\n /\nsum(rate(grpc_server_started_total{installation=~\"$installation\",grpc_type=\"server_stream\"}[1m])) by (grpc_service,grpc_method)",
     "legendFormat": "{{grpc_service}}.{{grpc_method}}"
    }
   ]
  }
 ]
}