{
 "title": "GBE Main",
 "description": "Dashboard for GBE",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(gbe_extractor_received_pulses, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(gbe_extractor_received_pulses, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Extractor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current extract pulse",
   "type": "singlestat",
   "description": "Current pulse extracting from platform",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "gbe_extractor_last_pulse{instance=~\"$instance\", job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "From extractor queue",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "gbe_extractor_data_queue{instance=~\"$instance\", job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Parallel connections",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "gbe_extractor_process_count{instance=~\"$instance\", job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Received pulses rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gbe_extractor_received_pulses{instance=~\"$instance\", job=~\"$job\"}[2m])",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Received records rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gbe_extractor_received_records{instance=~\"$instance\", job=~\"$job\"}[2m])",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Errors rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gbe_extractor_errors{instance=~\"$instance\", job=~\"$job\"}[2m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Transformer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Pulses rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gbe_transformer_pulses{instance=~\"$instance\", job=~\"$job\"}[2m])",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Records rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gbe_transformer_records{instance=~\"$instance\", job=~\"$job\"}[2m])",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Errors rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gbe_transformer_errors{instance=~\"$instance\", job=~\"$job\"}[2m])",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "From transform queue",
   "type": "singlestat",
   "description": "The number of jetdrops in transformer export data queue",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "gbe_transformer_data_queue{instance=~\"$instance\", job=~\"$job\"}"
    }
   ]
  },
  { "title": "Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Current incomplete pulse",
   "type": "singlestat",
   "description": "Current incomplete pulse that records are rerequested from platform",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "gbe_controller_current_incomplete_pulse{instance=~\"$instance\", job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Current seq pulse",
   "type": "singlestat",
   "description": "Current sequentual pulse rerequested from platform",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "gbe_controller_current_seq_pulse{instance=~\"$instance\", job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Incomplete pulses queue",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "gbe_controller_data_queue{instance=~\"$instance\", job=~\"$job\"}"
    }
   ]
  }
 ]
}