package mock

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/insolar/block-explorer/etl/models"
)

// StorageMock implements interfaces.Storage
type StorageMock struct {
	t minimock.Tester

	funcGetRecord          func(ref models.Reference) (r1 models.Record, err error)
	inspectFuncGetRecord   func(ref models.Reference)
	afterGetRecordCounter  uint64
	beforeGetRecordCounter uint64
	GetRecordMock          mStorageMockGetRecord

	funcSaveJetDropData          func(jetDrop models.JetDrop, records []models.Record) (err error)
	inspectFuncSaveJetDropData   func(jetDrop models.JetDrop, records []models.Record)
	afterSaveJetDropDataCounter  uint64
	beforeSaveJetDropDataCounter uint64
	SaveJetDropDataMock          mStorageMockSaveJetDropData
}

// NewStorageMock returns a mock for interfaces.Storage
func NewStorageMock(t minimock.Tester) *StorageMock {
	m := &StorageMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetRecordMock = mStorageMockGetRecord{mock: m}
	m.GetRecordMock.callArgs = []*StorageMockGetRecordParams{}

	m.SaveJetDropDataMock = mStorageMockSaveJetDropData{mock: m}
	m.SaveJetDropDataMock.callArgs = []*StorageMockSaveJetDropDataParams{}

	return m
}

type mStorageMockGetRecord struct {
	mock               *StorageMock
	defaultExpectation *StorageMockGetRecordExpectation
	expectations       []*StorageMockGetRecordExpectation

	callArgs []*StorageMockGetRecordParams
	mutex    sync.RWMutex
}

// StorageMockGetRecordExpectation specifies expectation struct of the Storage.GetRecord
type StorageMockGetRecordExpectation struct {
	mock    *StorageMock
	params  *StorageMockGetRecordParams
	results *StorageMockGetRecordResults
	Counter uint64
}

// StorageMockGetRecordParams contains parameters of the Storage.GetRecord
type StorageMockGetRecordParams struct {
	ref models.Reference
}

// StorageMockGetRecordResults contains results of the Storage.GetRecord
type StorageMockGetRecordResults struct {
	r1  models.Record
	err error
}

// Expect sets up expected params for Storage.GetRecord
func (mmGetRecord *mStorageMockGetRecord) Expect(ref models.Reference) *mStorageMockGetRecord {
	if mmGetRecord.mock.funcGetRecord != nil {
		mmGetRecord.mock.t.Fatalf("StorageMock.GetRecord mock is already set by Set")
	}

	if mmGetRecord.defaultExpectation == nil {
		mmGetRecord.defaultExpectation = &StorageMockGetRecordExpectation{}
	}

	mmGetRecord.defaultExpectation.params = &StorageMockGetRecordParams{ref}
	for _, e := range mmGetRecord.expectations {
		if minimock.Equal(e.params, mmGetRecord.defaultExpectation.params) {
			mmGetRecord.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetRecord.defaultExpectation.params)
		}
	}

	return mmGetRecord
}

// Inspect accepts an inspector function that has same arguments as the Storage.GetRecord
func (mmGetRecord *mStorageMockGetRecord) Inspect(f func(ref models.Reference)) *mStorageMockGetRecord {
	if mmGetRecord.mock.inspectFuncGetRecord != nil {
		mmGetRecord.mock.t.Fatalf("Inspect function is already set for StorageMock.GetRecord")
	}

	mmGetRecord.mock.inspectFuncGetRecord = f

	return mmGetRecord
}

// Return sets up results that will be returned by Storage.GetRecord
func (mmGetRecord *mStorageMockGetRecord) Return(r1 models.Record, err error) *StorageMock {
	if mmGetRecord.mock.funcGetRecord != nil {
		mmGetRecord.mock.t.Fatalf("StorageMock.GetRecord mock is already set by Set")
	}

	if mmGetRecord.defaultExpectation == nil {
		mmGetRecord.defaultExpectation = &StorageMockGetRecordExpectation{mock: mmGetRecord.mock}
	}
	mmGetRecord.defaultExpectation.results = &StorageMockGetRecordResults{r1, err}
	return mmGetRecord.mock
}

//Set uses given function f to mock the Storage.GetRecord method
func (mmGetRecord *mStorageMockGetRecord) Set(f func(ref models.Reference) (r1 models.Record, err error)) *StorageMock {
	if mmGetRecord.defaultExpectation != nil {
		mmGetRecord.mock.t.Fatalf("Default expectation is already set for the Storage.GetRecord method")
	}

	if len(mmGetRecord.expectations) > 0 {
		mmGetRecord.mock.t.Fatalf("Some expectations are already set for the Storage.GetRecord method")
	}

	mmGetRecord.mock.funcGetRecord = f
	return mmGetRecord.mock
}

// When sets expectation for the Storage.GetRecord which will trigger the result defined by the following
// Then helper
func (mmGetRecord *mStorageMockGetRecord) When(ref models.Reference) *StorageMockGetRecordExpectation {
	if mmGetRecord.mock.funcGetRecord != nil {
		mmGetRecord.mock.t.Fatalf("StorageMock.GetRecord mock is already set by Set")
	}

	expectation := &StorageMockGetRecordExpectation{
		mock:   mmGetRecord.mock,
		params: &StorageMockGetRecordParams{ref},
	}
	mmGetRecord.expectations = append(mmGetRecord.expectations, expectation)
	return expectation
}

// Then sets up Storage.GetRecord return parameters for the expectation previously defined by the When method
func (e *StorageMockGetRecordExpectation) Then(r1 models.Record, err error) *StorageMock {
	e.results = &StorageMockGetRecordResults{r1, err}
	return e.mock
}

// GetRecord implements interfaces.Storage
func (mmGetRecord *StorageMock) GetRecord(ref models.Reference) (r1 models.Record, err error) {
	mm_atomic.AddUint64(&mmGetRecord.beforeGetRecordCounter, 1)
	defer mm_atomic.AddUint64(&mmGetRecord.afterGetRecordCounter, 1)

	if mmGetRecord.inspectFuncGetRecord != nil {
		mmGetRecord.inspectFuncGetRecord(ref)
	}

	mm_params := &StorageMockGetRecordParams{ref}

	// Record call args
	mmGetRecord.GetRecordMock.mutex.Lock()
	mmGetRecord.GetRecordMock.callArgs = append(mmGetRecord.GetRecordMock.callArgs, mm_params)
	mmGetRecord.GetRecordMock.mutex.Unlock()

	for _, e := range mmGetRecord.GetRecordMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.r1, e.results.err
		}
	}

	if mmGetRecord.GetRecordMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetRecord.GetRecordMock.defaultExpectation.Counter, 1)
		mm_want := mmGetRecord.GetRecordMock.defaultExpectation.params
		mm_got := StorageMockGetRecordParams{ref}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetRecord.t.Errorf("StorageMock.GetRecord got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetRecord.GetRecordMock.defaultExpectation.results
		if mm_results == nil {
			mmGetRecord.t.Fatal("No results are set for the StorageMock.GetRecord")
		}
		return (*mm_results).r1, (*mm_results).err
	}
	if mmGetRecord.funcGetRecord != nil {
		return mmGetRecord.funcGetRecord(ref)
	}
	mmGetRecord.t.Fatalf("Unexpected call to StorageMock.GetRecord. %v", ref)
	return
}

// GetRecordAfterCounter returns a count of finished StorageMock.GetRecord invocations
func (mmGetRecord *StorageMock) GetRecordAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetRecord.afterGetRecordCounter)
}

// GetRecordBeforeCounter returns a count of StorageMock.GetRecord invocations
func (mmGetRecord *StorageMock) GetRecordBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetRecord.beforeGetRecordCounter)
}

// Calls returns a list of arguments used in each call to StorageMock.GetRecord.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetRecord *mStorageMockGetRecord) Calls() []*StorageMockGetRecordParams {
	mmGetRecord.mutex.RLock()

	argCopy := make([]*StorageMockGetRecordParams, len(mmGetRecord.callArgs))
	copy(argCopy, mmGetRecord.callArgs)

	mmGetRecord.mutex.RUnlock()

	return argCopy
}

// MinimockGetRecordDone returns true if the count of the GetRecord invocations corresponds
// the number of defined expectations
func (m *StorageMock) MinimockGetRecordDone() bool {
	for _, e := range m.GetRecordMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetRecordMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetRecordCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetRecord != nil && mm_atomic.LoadUint64(&m.afterGetRecordCounter) < 1 {
		return false
	}
	return true
}

// MinimockGetRecordInspect logs each unmet expectation
func (m *StorageMock) MinimockGetRecordInspect() {
	for _, e := range m.GetRecordMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StorageMock.GetRecord with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetRecordMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetRecordCounter) < 1 {
		if m.GetRecordMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to StorageMock.GetRecord")
		} else {
			m.t.Errorf("Expected call to StorageMock.GetRecord with params: %#v", *m.GetRecordMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetRecord != nil && mm_atomic.LoadUint64(&m.afterGetRecordCounter) < 1 {
		m.t.Error("Expected call to StorageMock.GetRecord")
	}
}

type mStorageMockSaveJetDropData struct {
	mock               *StorageMock
	defaultExpectation *StorageMockSaveJetDropDataExpectation
	expectations       []*StorageMockSaveJetDropDataExpectation

	callArgs []*StorageMockSaveJetDropDataParams
	mutex    sync.RWMutex
}

// StorageMockSaveJetDropDataExpectation specifies expectation struct of the Storage.SaveJetDropData
type StorageMockSaveJetDropDataExpectation struct {
	mock    *StorageMock
	params  *StorageMockSaveJetDropDataParams
	results *StorageMockSaveJetDropDataResults
	Counter uint64
}

// StorageMockSaveJetDropDataParams contains parameters of the Storage.SaveJetDropData
type StorageMockSaveJetDropDataParams struct {
	jetDrop models.JetDrop
	records []models.Record
}

// StorageMockSaveJetDropDataResults contains results of the Storage.SaveJetDropData
type StorageMockSaveJetDropDataResults struct {
	err error
}

// Expect sets up expected params for Storage.SaveJetDropData
func (mmSaveJetDropData *mStorageMockSaveJetDropData) Expect(jetDrop models.JetDrop, records []models.Record) *mStorageMockSaveJetDropData {
	if mmSaveJetDropData.mock.funcSaveJetDropData != nil {
		mmSaveJetDropData.mock.t.Fatalf("StorageMock.SaveJetDropData mock is already set by Set")
	}

	if mmSaveJetDropData.defaultExpectation == nil {
		mmSaveJetDropData.defaultExpectation = &StorageMockSaveJetDropDataExpectation{}
	}

	mmSaveJetDropData.defaultExpectation.params = &StorageMockSaveJetDropDataParams{jetDrop, records}
	for _, e := range mmSaveJetDropData.expectations {
		if minimock.Equal(e.params, mmSaveJetDropData.defaultExpectation.params) {
			mmSaveJetDropData.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSaveJetDropData.defaultExpectation.params)
		}
	}

	return mmSaveJetDropData
}

// Inspect accepts an inspector function that has same arguments as the Storage.SaveJetDropData
func (mmSaveJetDropData *mStorageMockSaveJetDropData) Inspect(f func(jetDrop models.JetDrop, records []models.Record)) *mStorageMockSaveJetDropData {
	if mmSaveJetDropData.mock.inspectFuncSaveJetDropData != nil {
		mmSaveJetDropData.mock.t.Fatalf("Inspect function is already set for StorageMock.SaveJetDropData")
	}

	mmSaveJetDropData.mock.inspectFuncSaveJetDropData = f

	return mmSaveJetDropData
}

// Return sets up results that will be returned by Storage.SaveJetDropData
func (mmSaveJetDropData *mStorageMockSaveJetDropData) Return(err error) *StorageMock {
	if mmSaveJetDropData.mock.funcSaveJetDropData != nil {
		mmSaveJetDropData.mock.t.Fatalf("StorageMock.SaveJetDropData mock is already set by Set")
	}

	if mmSaveJetDropData.defaultExpectation == nil {
		mmSaveJetDropData.defaultExpectation = &StorageMockSaveJetDropDataExpectation{mock: mmSaveJetDropData.mock}
	}
	mmSaveJetDropData.defaultExpectation.results = &StorageMockSaveJetDropDataResults{err}
	return mmSaveJetDropData.mock
}

//Set uses given function f to mock the Storage.SaveJetDropData method
func (mmSaveJetDropData *mStorageMockSaveJetDropData) Set(f func(jetDrop models.JetDrop, records []models.Record) (err error)) *StorageMock {
	if mmSaveJetDropData.defaultExpectation != nil {
		mmSaveJetDropData.mock.t.Fatalf("Default expectation is already set for the Storage.SaveJetDropData method")
	}

	if len(mmSaveJetDropData.expectations) > 0 {
		mmSaveJetDropData.mock.t.Fatalf("Some expectations are already set for the Storage.SaveJetDropData method")
	}

	mmSaveJetDropData.mock.funcSaveJetDropData = f
	return mmSaveJetDropData.mock
}

// When sets expectation for the Storage.SaveJetDropData which will trigger the result defined by the following
// Then helper
func (mmSaveJetDropData *mStorageMockSaveJetDropData) When(jetDrop models.JetDrop, records []models.Record) *StorageMockSaveJetDropDataExpectation {
	if mmSaveJetDropData.mock.funcSaveJetDropData != nil {
		mmSaveJetDropData.mock.t.Fatalf("StorageMock.SaveJetDropData mock is already set by Set")
	}

	expectation := &StorageMockSaveJetDropDataExpectation{
		mock:   mmSaveJetDropData.mock,
		params: &StorageMockSaveJetDropDataParams{jetDrop, records},
	}
	mmSaveJetDropData.expectations = append(mmSaveJetDropData.expectations, expectation)
	return expectation
}

// Then sets up Storage.SaveJetDropData return parameters for the expectation previously defined by the When method
func (e *StorageMockSaveJetDropDataExpectation) Then(err error) *StorageMock {
	e.results = &StorageMockSaveJetDropDataResults{err}
	return e.mock
}

// SaveJetDropData implements interfaces.Storage
func (mmSaveJetDropData *StorageMock) SaveJetDropData(jetDrop models.JetDrop, records []models.Record) (err error) {
	mm_atomic.AddUint64(&mmSaveJetDropData.beforeSaveJetDropDataCounter, 1)
	defer mm_atomic.AddUint64(&mmSaveJetDropData.afterSaveJetDropDataCounter, 1)

	if mmSaveJetDropData.inspectFuncSaveJetDropData != nil {
		mmSaveJetDropData.inspectFuncSaveJetDropData(jetDrop, records)
	}

	mm_params := &StorageMockSaveJetDropDataParams{jetDrop, records}

	// Record call args
	mmSaveJetDropData.SaveJetDropDataMock.mutex.Lock()
	mmSaveJetDropData.SaveJetDropDataMock.callArgs = append(mmSaveJetDropData.SaveJetDropDataMock.callArgs, mm_params)
	mmSaveJetDropData.SaveJetDropDataMock.mutex.Unlock()

	for _, e := range mmSaveJetDropData.SaveJetDropDataMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSaveJetDropData.SaveJetDropDataMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSaveJetDropData.SaveJetDropDataMock.defaultExpectation.Counter, 1)
		mm_want := mmSaveJetDropData.SaveJetDropDataMock.defaultExpectation.params
		mm_got := StorageMockSaveJetDropDataParams{jetDrop, records}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSaveJetDropData.t.Errorf("StorageMock.SaveJetDropData got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSaveJetDropData.SaveJetDropDataMock.defaultExpectation.results
		if mm_results == nil {
			mmSaveJetDropData.t.Fatal("No results are set for the StorageMock.SaveJetDropData")
		}
		return (*mm_results).err
	}
	if mmSaveJetDropData.funcSaveJetDropData != nil {
		return mmSaveJetDropData.funcSaveJetDropData(jetDrop, records)
	}
	mmSaveJetDropData.t.Fatalf("Unexpected call to StorageMock.SaveJetDropData. %v %v", jetDrop, records)
	return
}

// SaveJetDropDataAfterCounter returns a count of finished StorageMock.SaveJetDropData invocations
func (mmSaveJetDropData *StorageMock) SaveJetDropDataAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSaveJetDropData.afterSaveJetDropDataCounter)
}

// SaveJetDropDataBeforeCounter returns a count of StorageMock.SaveJetDropData invocations
func (mmSaveJetDropData *StorageMock) SaveJetDropDataBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSaveJetDropData.beforeSaveJetDropDataCounter)
}

// Calls returns a list of arguments used in each call to StorageMock.SaveJetDropData.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSaveJetDropData *mStorageMockSaveJetDropData) Calls() []*StorageMockSaveJetDropDataParams {
	mmSaveJetDropData.mutex.RLock()

	argCopy := make([]*StorageMockSaveJetDropDataParams, len(mmSaveJetDropData.callArgs))
	copy(argCopy, mmSaveJetDropData.callArgs)

	mmSaveJetDropData.mutex.RUnlock()

	return argCopy
}

// MinimockSaveJetDropDataDone returns true if the count of the SaveJetDropData invocations corresponds
// the number of defined expectations
func (m *StorageMock) MinimockSaveJetDropDataDone() bool {
	for _, e := range m.SaveJetDropDataMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.SaveJetDropDataMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterSaveJetDropDataCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSaveJetDropData != nil && mm_atomic.LoadUint64(&m.afterSaveJetDropDataCounter) < 1 {
		return false
	}
	return true
}

// MinimockSaveJetDropDataInspect logs each unmet expectation
func (m *StorageMock) MinimockSaveJetDropDataInspect() {
	for _, e := range m.SaveJetDropDataMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StorageMock.SaveJetDropData with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.SaveJetDropDataMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterSaveJetDropDataCounter) < 1 {
		if m.SaveJetDropDataMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to StorageMock.SaveJetDropData")
		} else {
			m.t.Errorf("Expected call to StorageMock.SaveJetDropData with params: %#v", *m.SaveJetDropDataMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSaveJetDropData != nil && mm_atomic.LoadUint64(&m.afterSaveJetDropDataCounter) < 1 {
		m.t.Error("Expected call to StorageMock.SaveJetDropData")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *StorageMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockGetRecordInspect()

		m.MinimockSaveJetDropDataInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *StorageMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *StorageMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetRecordDone() &&
		m.MinimockSaveJetDropDataDone()
}
