package mock

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// ConnectionManagerMock implements etl.ConnectionManager
type ConnectionManagerMock struct {
	t minimock.Tester

	funcStart          func(ctx context.Context) (err error)
	inspectFuncStart   func(ctx context.Context)
	afterStartCounter  uint64
	beforeStartCounter uint64
	StartMock          mConnectionManagerMockStart

	funcStop          func(ctx context.Context) (err error)
	inspectFuncStop   func(ctx context.Context)
	afterStopCounter  uint64
	beforeStopCounter uint64
	StopMock          mConnectionManagerMockStop
}

// NewConnectionManagerMock returns a mock for etl.ConnectionManager
func NewConnectionManagerMock(t minimock.Tester) *ConnectionManagerMock {
	m := &ConnectionManagerMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.StartMock = mConnectionManagerMockStart{mock: m}
	m.StartMock.callArgs = []*ConnectionManagerMockStartParams{}

	m.StopMock = mConnectionManagerMockStop{mock: m}
	m.StopMock.callArgs = []*ConnectionManagerMockStopParams{}

	return m
}

type mConnectionManagerMockStart struct {
	mock               *ConnectionManagerMock
	defaultExpectation *ConnectionManagerMockStartExpectation
	expectations       []*ConnectionManagerMockStartExpectation

	callArgs []*ConnectionManagerMockStartParams
	mutex    sync.RWMutex
}

// ConnectionManagerMockStartExpectation specifies expectation struct of the ConnectionManager.Start
type ConnectionManagerMockStartExpectation struct {
	mock    *ConnectionManagerMock
	params  *ConnectionManagerMockStartParams
	results *ConnectionManagerMockStartResults
	Counter uint64
}

// ConnectionManagerMockStartParams contains parameters of the ConnectionManager.Start
type ConnectionManagerMockStartParams struct {
	ctx context.Context
}

// ConnectionManagerMockStartResults contains results of the ConnectionManager.Start
type ConnectionManagerMockStartResults struct {
	err error
}

// Expect sets up expected params for ConnectionManager.Start
func (mmStart *mConnectionManagerMockStart) Expect(ctx context.Context) *mConnectionManagerMockStart {
	if mmStart.mock.funcStart != nil {
		mmStart.mock.t.Fatalf("ConnectionManagerMock.Start mock is already set by Set")
	}

	if mmStart.defaultExpectation == nil {
		mmStart.defaultExpectation = &ConnectionManagerMockStartExpectation{}
	}

	mmStart.defaultExpectation.params = &ConnectionManagerMockStartParams{ctx}
	for _, e := range mmStart.expectations {
		if minimock.Equal(e.params, mmStart.defaultExpectation.params) {
			mmStart.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmStart.defaultExpectation.params)
		}
	}

	return mmStart
}

// Inspect accepts an inspector function that has same arguments as the ConnectionManager.Start
func (mmStart *mConnectionManagerMockStart) Inspect(f func(ctx context.Context)) *mConnectionManagerMockStart {
	if mmStart.mock.inspectFuncStart != nil {
		mmStart.mock.t.Fatalf("Inspect function is already set for ConnectionManagerMock.Start")
	}

	mmStart.mock.inspectFuncStart = f

	return mmStart
}

// Return sets up results that will be returned by ConnectionManager.Start
func (mmStart *mConnectionManagerMockStart) Return(err error) *ConnectionManagerMock {
	if mmStart.mock.funcStart != nil {
		mmStart.mock.t.Fatalf("ConnectionManagerMock.Start mock is already set by Set")
	}

	if mmStart.defaultExpectation == nil {
		mmStart.defaultExpectation = &ConnectionManagerMockStartExpectation{mock: mmStart.mock}
	}
	mmStart.defaultExpectation.results = &ConnectionManagerMockStartResults{err}
	return mmStart.mock
}

//Set uses given function f to mock the ConnectionManager.Start method
func (mmStart *mConnectionManagerMockStart) Set(f func(ctx context.Context) (err error)) *ConnectionManagerMock {
	if mmStart.defaultExpectation != nil {
		mmStart.mock.t.Fatalf("Default expectation is already set for the ConnectionManager.Start method")
	}

	if len(mmStart.expectations) > 0 {
		mmStart.mock.t.Fatalf("Some expectations are already set for the ConnectionManager.Start method")
	}

	mmStart.mock.funcStart = f
	return mmStart.mock
}

// When sets expectation for the ConnectionManager.Start which will trigger the result defined by the following
// Then helper
func (mmStart *mConnectionManagerMockStart) When(ctx context.Context) *ConnectionManagerMockStartExpectation {
	if mmStart.mock.funcStart != nil {
		mmStart.mock.t.Fatalf("ConnectionManagerMock.Start mock is already set by Set")
	}

	expectation := &ConnectionManagerMockStartExpectation{
		mock:   mmStart.mock,
		params: &ConnectionManagerMockStartParams{ctx},
	}
	mmStart.expectations = append(mmStart.expectations, expectation)
	return expectation
}

// Then sets up ConnectionManager.Start return parameters for the expectation previously defined by the When method
func (e *ConnectionManagerMockStartExpectation) Then(err error) *ConnectionManagerMock {
	e.results = &ConnectionManagerMockStartResults{err}
	return e.mock
}

// Start implements etl.ConnectionManager
func (mmStart *ConnectionManagerMock) Start(ctx context.Context) (err error) {
	mm_atomic.AddUint64(&mmStart.beforeStartCounter, 1)
	defer mm_atomic.AddUint64(&mmStart.afterStartCounter, 1)

	if mmStart.inspectFuncStart != nil {
		mmStart.inspectFuncStart(ctx)
	}

	mm_params := &ConnectionManagerMockStartParams{ctx}

	// Record call args
	mmStart.StartMock.mutex.Lock()
	mmStart.StartMock.callArgs = append(mmStart.StartMock.callArgs, mm_params)
	mmStart.StartMock.mutex.Unlock()

	for _, e := range mmStart.StartMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmStart.StartMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmStart.StartMock.defaultExpectation.Counter, 1)
		mm_want := mmStart.StartMock.defaultExpectation.params
		mm_got := ConnectionManagerMockStartParams{ctx}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmStart.t.Errorf("ConnectionManagerMock.Start got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmStart.StartMock.defaultExpectation.results
		if mm_results == nil {
			mmStart.t.Fatal("No results are set for the ConnectionManagerMock.Start")
		}
		return (*mm_results).err
	}
	if mmStart.funcStart != nil {
		return mmStart.funcStart(ctx)
	}
	mmStart.t.Fatalf("Unexpected call to ConnectionManagerMock.Start. %v", ctx)
	return
}

// StartAfterCounter returns a count of finished ConnectionManagerMock.Start invocations
func (mmStart *ConnectionManagerMock) StartAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStart.afterStartCounter)
}

// StartBeforeCounter returns a count of ConnectionManagerMock.Start invocations
func (mmStart *ConnectionManagerMock) StartBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStart.beforeStartCounter)
}

// Calls returns a list of arguments used in each call to ConnectionManagerMock.Start.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmStart *mConnectionManagerMockStart) Calls() []*ConnectionManagerMockStartParams {
	mmStart.mutex.RLock()

	argCopy := make([]*ConnectionManagerMockStartParams, len(mmStart.callArgs))
	copy(argCopy, mmStart.callArgs)

	mmStart.mutex.RUnlock()

	return argCopy
}

// MinimockStartDone returns true if the count of the Start invocations corresponds
// the number of defined expectations
func (m *ConnectionManagerMock) MinimockStartDone() bool {
	for _, e := range m.StartMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.StartMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterStartCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcStart != nil && mm_atomic.LoadUint64(&m.afterStartCounter) < 1 {
		return false
	}
	return true
}

// MinimockStartInspect logs each unmet expectation
func (m *ConnectionManagerMock) MinimockStartInspect() {
	for _, e := range m.StartMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ConnectionManagerMock.Start with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.StartMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterStartCounter) < 1 {
		if m.StartMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to ConnectionManagerMock.Start")
		} else {
			m.t.Errorf("Expected call to ConnectionManagerMock.Start with params: %#v", *m.StartMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcStart != nil && mm_atomic.LoadUint64(&m.afterStartCounter) < 1 {
		m.t.Error("Expected call to ConnectionManagerMock.Start")
	}
}

type mConnectionManagerMockStop struct {
	mock               *ConnectionManagerMock
	defaultExpectation *ConnectionManagerMockStopExpectation
	expectations       []*ConnectionManagerMockStopExpectation

	callArgs []*ConnectionManagerMockStopParams
	mutex    sync.RWMutex
}

// ConnectionManagerMockStopExpectation specifies expectation struct of the ConnectionManager.Stop
type ConnectionManagerMockStopExpectation struct {
	mock    *ConnectionManagerMock
	params  *ConnectionManagerMockStopParams
	results *ConnectionManagerMockStopResults
	Counter uint64
}

// ConnectionManagerMockStopParams contains parameters of the ConnectionManager.Stop
type ConnectionManagerMockStopParams struct {
	ctx context.Context
}

// ConnectionManagerMockStopResults contains results of the ConnectionManager.Stop
type ConnectionManagerMockStopResults struct {
	err error
}

// Expect sets up expected params for ConnectionManager.Stop
func (mmStop *mConnectionManagerMockStop) Expect(ctx context.Context) *mConnectionManagerMockStop {
	if mmStop.mock.funcStop != nil {
		mmStop.mock.t.Fatalf("ConnectionManagerMock.Stop mock is already set by Set")
	}

	if mmStop.defaultExpectation == nil {
		mmStop.defaultExpectation = &ConnectionManagerMockStopExpectation{}
	}

	mmStop.defaultExpectation.params = &ConnectionManagerMockStopParams{ctx}
	for _, e := range mmStop.expectations {
		if minimock.Equal(e.params, mmStop.defaultExpectation.params) {
			mmStop.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmStop.defaultExpectation.params)
		}
	}

	return mmStop
}

// Inspect accepts an inspector function that has same arguments as the ConnectionManager.Stop
func (mmStop *mConnectionManagerMockStop) Inspect(f func(ctx context.Context)) *mConnectionManagerMockStop {
	if mmStop.mock.inspectFuncStop != nil {
		mmStop.mock.t.Fatalf("Inspect function is already set for ConnectionManagerMock.Stop")
	}

	mmStop.mock.inspectFuncStop = f

	return mmStop
}

// Return sets up results that will be returned by ConnectionManager.Stop
func (mmStop *mConnectionManagerMockStop) Return(err error) *ConnectionManagerMock {
	if mmStop.mock.funcStop != nil {
		mmStop.mock.t.Fatalf("ConnectionManagerMock.Stop mock is already set by Set")
	}

	if mmStop.defaultExpectation == nil {
		mmStop.defaultExpectation = &ConnectionManagerMockStopExpectation{mock: mmStop.mock}
	}
	mmStop.defaultExpectation.results = &ConnectionManagerMockStopResults{err}
	return mmStop.mock
}

//Set uses given function f to mock the ConnectionManager.Stop method
func (mmStop *mConnectionManagerMockStop) Set(f func(ctx context.Context) (err error)) *ConnectionManagerMock {
	if mmStop.defaultExpectation != nil {
		mmStop.mock.t.Fatalf("Default expectation is already set for the ConnectionManager.Stop method")
	}

	if len(mmStop.expectations) > 0 {
		mmStop.mock.t.Fatalf("Some expectations are already set for the ConnectionManager.Stop method")
	}

	mmStop.mock.funcStop = f
	return mmStop.mock
}

// When sets expectation for the ConnectionManager.Stop which will trigger the result defined by the following
// Then helper
func (mmStop *mConnectionManagerMockStop) When(ctx context.Context) *ConnectionManagerMockStopExpectation {
	if mmStop.mock.funcStop != nil {
		mmStop.mock.t.Fatalf("ConnectionManagerMock.Stop mock is already set by Set")
	}

	expectation := &ConnectionManagerMockStopExpectation{
		mock:   mmStop.mock,
		params: &ConnectionManagerMockStopParams{ctx},
	}
	mmStop.expectations = append(mmStop.expectations, expectation)
	return expectation
}

// Then sets up ConnectionManager.Stop return parameters for the expectation previously defined by the When method
func (e *ConnectionManagerMockStopExpectation) Then(err error) *ConnectionManagerMock {
	e.results = &ConnectionManagerMockStopResults{err}
	return e.mock
}

// Stop implements etl.ConnectionManager
func (mmStop *ConnectionManagerMock) Stop(ctx context.Context) (err error) {
	mm_atomic.AddUint64(&mmStop.beforeStopCounter, 1)
	defer mm_atomic.AddUint64(&mmStop.afterStopCounter, 1)

	if mmStop.inspectFuncStop != nil {
		mmStop.inspectFuncStop(ctx)
	}

	mm_params := &ConnectionManagerMockStopParams{ctx}

	// Record call args
	mmStop.StopMock.mutex.Lock()
	mmStop.StopMock.callArgs = append(mmStop.StopMock.callArgs, mm_params)
	mmStop.StopMock.mutex.Unlock()

	for _, e := range mmStop.StopMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmStop.StopMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmStop.StopMock.defaultExpectation.Counter, 1)
		mm_want := mmStop.StopMock.defaultExpectation.params
		mm_got := ConnectionManagerMockStopParams{ctx}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmStop.t.Errorf("ConnectionManagerMock.Stop got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmStop.StopMock.defaultExpectation.results
		if mm_results == nil {
			mmStop.t.Fatal("No results are set for the ConnectionManagerMock.Stop")
		}
		return (*mm_results).err
	}
	if mmStop.funcStop != nil {
		return mmStop.funcStop(ctx)
	}
	mmStop.t.Fatalf("Unexpected call to ConnectionManagerMock.Stop. %v", ctx)
	return
}

// StopAfterCounter returns a count of finished ConnectionManagerMock.Stop invocations
func (mmStop *ConnectionManagerMock) StopAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStop.afterStopCounter)
}

// StopBeforeCounter returns a count of ConnectionManagerMock.Stop invocations
func (mmStop *ConnectionManagerMock) StopBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStop.beforeStopCounter)
}

// Calls returns a list of arguments used in each call to ConnectionManagerMock.Stop.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmStop *mConnectionManagerMockStop) Calls() []*ConnectionManagerMockStopParams {
	mmStop.mutex.RLock()

	argCopy := make([]*ConnectionManagerMockStopParams, len(mmStop.callArgs))
	copy(argCopy, mmStop.callArgs)

	mmStop.mutex.RUnlock()

	return argCopy
}

// MinimockStopDone returns true if the count of the Stop invocations corresponds
// the number of defined expectations
func (m *ConnectionManagerMock) MinimockStopDone() bool {
	for _, e := range m.StopMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.StopMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterStopCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcStop != nil && mm_atomic.LoadUint64(&m.afterStopCounter) < 1 {
		return false
	}
	return true
}

// MinimockStopInspect logs each unmet expectation
func (m *ConnectionManagerMock) MinimockStopInspect() {
	for _, e := range m.StopMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ConnectionManagerMock.Stop with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.StopMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterStopCounter) < 1 {
		if m.StopMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to ConnectionManagerMock.Stop")
		} else {
			m.t.Errorf("Expected call to ConnectionManagerMock.Stop with params: %#v", *m.StopMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcStop != nil && mm_atomic.LoadUint64(&m.afterStopCounter) < 1 {
		m.t.Error("Expected call to ConnectionManagerMock.Stop")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ConnectionManagerMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockStartInspect()

		m.MinimockStopInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ConnectionManagerMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ConnectionManagerMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockStartDone() &&
		m.MinimockStopDone()
}
