name: build
on:
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+
    branches:
    - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Set repo and image name
      run: |
        REPO=$(echo "${{ github.repository }}" | cut -d/ -f2)
        IMAGE_NAME=${REPO}
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        echo "::set-env name=REPO::${REPO}"
        echo "::set-env name=IMAGE_NAME::${IMAGE_NAME}"
        echo "::set-env name=VERSION::${VERSION}"
    - name: checkout sources
      uses: actions/checkout@v2
    - name: build docker image
      run: |
        docker build -t ${IMAGE_NAME} .
    - name: Log into registry
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Push image
      run: |
        [ "$VERSION" == "master" ] && VERSION=latest
        docker tag ${IMAGE_NAME} insolar/${IMAGE_NAME}:${VERSION}
        docker push insolar/${IMAGE_NAME}:${VERSION}
